name: Version CI

on:
  push:
    branches:
      - master

jobs:
  version-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ardalanamini/auto-changelog@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
