name: Version CI

on:
  push:

jobs:
  version-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ardalanamini/auto-changelog@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit files
      run: |
        VERSION=$(<VERSION)
        git add .
        git config --local user.email "$github_email"
        git config --local user.name "$github_username"
        sudo git commit -m "v$VERSION" -m "" -a
      env:
        github_email: ${{ secrets.GITHUB_EMAIL }}
        github_username: ${{ secrets.GITHUB_USERNAME }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
